name = "MyPkg20"
uuid = "81fa98f4-1a90-4ec0-8abc-e015e890d478"
authors = ["Shuhei Ohno"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.11"
